################################################################################
## This file overrides config settings for the "development" environment
################################################################################

imports:
    - { resource : config.yml }

framework:

    logger:

        # log to console for development mode
        default:
            type: console
            level: DEBUG
